-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 'v0.4.1'
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/hootsuite/pre-commit-php.git
    sha: '1.0.0'
    hooks:
    -   id: php-lint
